### ISSUE TITLE
Publish patch release for Typescript definition

### ISSUE THREAD

**Issue by DenisCarriere** [mapbox/tiletype#18]
Could we publish a patch release `0.3.1` to enable the Typescript definitions [`index.d.ts`](https://github.com/mapbox/tiletype/blob/master/index.d.ts).
Thanks 😄

**Comment by DenisCarriere** [comment]
@tmcw @mcwhittemore Could you bump the npm release?

**Comment by tmcw** [comment]
👍 Published v0.3.1!

**Comment by DenisCarriere** [comment]
Yay! You're my hero 🚀
